### ISSUE TITLE
read the docs - but where?

### ISSUE THREAD

**Issue by FireLizard** [AlfonsoFilho/ClipPath#1]
Hi,
thank you for that poly-fill. 
But can you explain how to use it. Would be very nice ;)

Greetings
FireLizard

**Comment by victorbadila** [comment]
+1 on this
needs documentation

**Comment by gemmadlou** [comment]
+1 

All you have to do I believe is:
$(selector).ClipPath();

You also need to add:
data-clip="0 60px, 100% 0, 100% 100%, 12px 100%" to the dom element you're selecting.

However, I haven't gotten this to work ie IE9 as of yet.

**Comment by AlfonsoFilho** [comment]
Sorry took too much time to answer. I was too busy on private projects, now I'm trying to contributing more to open source community.
I've made many changes on latest commits. No breaking changes. In a nutshell:
- Added some tests;
- Ported lib to vanilla js. jQuery is no more a hard dependency;
- But jQuery still supported;
- Added examples;
- Minimal documentation added to README.
