### ISSUE TITLE
jQuery selector, explicit path required

### ISSUE THREAD

**Issue by peppertom** [AlfonsoFilho/ClipPath#4]
Hello @AlfonsoFilho,

Calling ClipPath on a jQuery object needs an explicit declaration of the **path**, e.g. in the example it's correct, but in the readme it's a bit misleading: 

`$('.image').ClipPath({path:'5% 5%, 100% 0%, 100% 75%, 75% 75%, 75% 100%'});`

instead of 

`$('.target').ClipPath('5% 5%, 100% 0%, 100% 75%');`

Thanks.

**Comment by AlfonsoFilho** [comment]
Apologies for that. In addition, instead of simply correcting the readme, I changed the ClipPath contract on jQuery implementation. So you should use a string. But this is not a breaking change. Use of object with path property still supported but deprecated.
