### ISSUE TITLE
Support for IE 11 / Edge

### ISSUE THREAD

**Issue by bkfarnsworth** [AlfonsoFilho/ClipPath#6]
Should this work for MS browsers? I tried and it didn't seem to work like it did in Chrome.

**Comment by isabisa** [comment]
I second this question.

**Comment by theDyingMountain** [comment]
I second this question too.

**Comment by AbdelTjuna** [comment]
Bumping this.

**Comment by AlfonsoFilho** [comment]
Sorry, it is not really working on IE. After a quick look on this seems IE will need some other approach.  Maybe replace dynamically the `<img />` with an `<svg><image /></svg>` in order the apply the clip-path. Not sure yet.

**Comment by strarsis** [comment]
Ironically Edge and Internet Explorer (OK, and Opera Mini) are the only browsers left that don't support `clip-path` yet (see https://caniuse.com/#feat=css-clip-path).

@AlfonsoFilho: Wrapping the `<img />` into a `<svg>` works indeed - however, I need also support for `srcset`. Using external SVGs prevents in turn loading a `<image` using `xlink:href` inside the SVG.
So I can either have the `clip-path` effect and not `srcset` or `srcset` and no `clip-path` effect.
`<foreignObject>` would be great for wrapping the HTML into a SVG, but Internet Explorer doesn't support it (Edge does though, maybe this can be used as a starting point).

**Comment by cvaize** [comment]
I added a polyphile for Edge, and fixed 1 bug in Mozilla. 
`
function applyClipPath(element, pathPoints, _supportPolygon) {

	_supportPolygon = typeof _supportPolygon !== 'undefined' ? _supportPolygon : hasSupportToPolygon;

	// Chrome / Safari
	if(typeof(element.style.webkitClipPath) !== 'undefined'){

		element.style.webkitClipPath = 'polygon(' + pathPoints + ')';

		// Unprefixed support
	} else if(_supportPolygon){

		element.style.clipPath = 'polygon(' + pathPoints + ')';

		// SVG
	} else {
		//Edge
		if(window.navigator.userAgent.indexOf("Edge") > -1){

			SVGPolyfill(element, pathPoints, true);

		//Other
		}else{
			SVGPolyfill(element, pathPoints);
		}
	}
}
`
`
function SVGPolyfill(element, pathPoints, edge) {

	// Remove units from path
	pathPoints = pathPoints.replace(/px|%|em/g, '');
	/**
	 * TODO: Rewrite the division by Regex
	 */
	let finishedPathPoints = '';
	let arrayPathPoints = pathPoints.split(', ');
	for (let i in arrayPathPoints)
	{
		let item = arrayPathPoints[i];
		let arrayPathPoint = item.split(' ');
		finishedPathPoints += (Number(arrayPathPoint[0])/100)+' '+(Number(arrayPathPoint[1])/100);
		if(i < (arrayPathPoints.length - 1)){
			finishedPathPoints += ', ';
		}
	}
	pathPoints = finishedPathPoints;

	let elClipPathId = element.getAttribute('data-clip-path-id');

	if(elClipPathId) {
		let actualPolygon = document.querySelector('#' + elClipPathId + ' > polygon');
		actualPolygon.setAttribute('points', pathPoints);
	} else {
		let clipPathID = getUniqueID();

		let svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
		svg.setAttribute('width', '0');
		svg.setAttribute('height', '0');
		svg.setAttributeNS('http://www.w3.org/2000/xmlns/', 'xmlns:xlink', 'http://www.w3.org/1999/xlink');

		if(edge){
			if(element.getAttribute('class')){
				svg.setAttribute('class', element.getAttribute('class'));
			}
			if(element.getAttribute('id')){
				svg.setAttribute('id', element.getAttribute('id'));
			}
			element.setAttribute('class', '');
			element.setAttribute('id', '');
			element.style.width = "100%";
			element.style.height = "100%";

			let defs = document.createElementNS('http://www.w3.org/2000/svg', 'defs');

			let clipPath = document.createElementNS('http://www.w3.org/2000/svg', 'clipPath');
			clipPath.setAttribute('id', clipPathID);
			clipPath.setAttribute('clipPathUnits', 'objectBoundingBox');

			let polygon = document.createElementNS('http://www.w3.org/2000/svg', 'polygon');
			polygon.setAttribute('points', pathPoints);

			let foreignObject = document.createElementNS('http://www.w3.org/2000/svg', 'foreignObject');
			foreignObject.setAttribute('clip-path', 'url(#'+clipPathID+')');
			foreignObject.setAttribute('width', '100%');
			foreignObject.setAttribute('height', '100%');

			foreignObject.appendChild(element.cloneNode(true));
			svg.appendChild(foreignObject);

			clipPath.appendChild(polygon);
			defs.appendChild(clipPath);
			svg.appendChild(defs);

			element.parentNode.replaceChild(svg, element);
		}else{
			let clipPath = document.createElementNS('http://www.w3.org/2000/svg', 'clipPath');
			clipPath.setAttribute('id', clipPathID);
			clipPath.setAttribute('clipPathUnits', 'objectBoundingBox');

			let polygon = document.createElementNS('http://www.w3.org/2000/svg', 'polygon');
			polygon.setAttribute('points', pathPoints);

			clipPath.appendChild(polygon);
			svg.appendChild(clipPath);
			document.body.appendChild(svg);
			element.setAttribute('data-clip-path-id', clipPathID);

			setTimeout(function () {
				element.style.clipPath = 'url(#' + clipPathID + ')';
			}, 0);
		}
	}
}
`

**Comment by strarsis** [comment]
@cvaize: Awesome! Could you create a Pull Request with these changes so it can be merged in?
@AlfonsoFilho: Are you still maintaining this repository?

**Comment by cvaize** [comment]
@strarsis: I slightly changed the code and tested it on Chrome, Mozilla and Edge. Works perfect with"%".  With other units of measurement will test later. I made a Fork and plan to make a Commit when I test "px" and "em". As well as after working with the new code for Production. 
`
function SVGPolyfill(element, pathPoints, edge) {


	// Remove units from path
	/**
	 * TODO: Rewrite the division by Regex
	 */
	let finishedPathPoints = '';
	let arrayPathPoints = pathPoints.split(', ');
	for (let i = 0; i < arrayPathPoints.length; i++)
	{
		let item = arrayPathPoints[i];
		let arrayPathPoint = item.split(' ');
		let lN = arrayPathPoint[0], rN = arrayPathPoint[1];
		if(lN.indexOf('%') !== -1){
			lN = lN.replace(/%/g, '');
			lN = (Number(lN)/100);
		}else{
			lN = lN.replace(/px|em/g, '');
		}
		if(rN.indexOf('%') !== -1){
			rN = rN.replace(/%/g, '');
			rN = (Number(rN)/100);
		}else{
			rN = rN.replace(/px|em/g, '');
		}
		finishedPathPoints += lN+' '+rN;
		if(i < (arrayPathPoints.length - 1)){
			finishedPathPoints += ', ';
		}
	}
	pathPoints = finishedPathPoints;

	let elClipPathId = element.getAttribute('data-clip-path-id');

	if(elClipPathId) {
		let actualPolygon = document.querySelector('#' + elClipPathId + ' > polygon');
		actualPolygon.setAttribute('points', pathPoints);
	} else {
		let clipPathID = getUniqueID();

		let svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
		svg.setAttribute('width', '0');
		svg.setAttribute('height', '0');
		svg.setAttributeNS('http://www.w3.org/2000/xmlns/', 'xmlns:xlink', 'http://www.w3.org/1999/xlink');

		if(edge){
			if(element.getAttribute('class')){
				svg.setAttribute('class', element.getAttribute('class'));
			}
			if(element.getAttribute('id')){
				svg.setAttribute('id', element.getAttribute('id'));
			}
			element.setAttribute('class', '');
			element.setAttribute('id', '');
			element.style.width = "100%";
			element.style.height = "100%";

			let defs = document.createElementNS('http://www.w3.org/2000/svg', 'defs');

			let clipPath = document.createElementNS('http://www.w3.org/2000/svg', 'clipPath');
			clipPath.setAttribute('id', clipPathID);
			clipPath.setAttribute('clipPathUnits', 'objectBoundingBox');

			let polygon = document.createElementNS('http://www.w3.org/2000/svg', 'polygon');
			polygon.setAttribute('points', pathPoints);

			let foreignObject = document.createElementNS('http://www.w3.org/2000/svg', 'foreignObject');
			foreignObject.setAttribute('clip-path', 'url(#'+clipPathID+')');
			foreignObject.setAttribute('width', '100%');
			foreignObject.setAttribute('height', '100%');

			foreignObject.appendChild(element.cloneNode(true));
			svg.appendChild(foreignObject);

			clipPath.appendChild(polygon);
			defs.appendChild(clipPath);
			svg.appendChild(defs);

			element.parentNode.replaceChild(svg, element);
		}else{
			let clipPath = document.createElementNS('http://www.w3.org/2000/svg', 'clipPath');
			clipPath.setAttribute('id', clipPathID);
			clipPath.setAttribute('clipPathUnits', 'objectBoundingBox');

			let polygon = document.createElementNS('http://www.w3.org/2000/svg', 'polygon');
			polygon.setAttribute('points', pathPoints);

			clipPath.appendChild(polygon);
			svg.appendChild(clipPath);
			document.body.appendChild(svg);
			element.setAttribute('data-clip-path-id', clipPathID);

			setTimeout(function () {
				element.style.clipPath = 'url(#' + clipPathID + ')';
			}, 0);
		}
	}
}

`
`
function applyClipPath(element, pathPoints, _supportPolygon) {

	_supportPolygon = typeof _supportPolygon !== 'undefined' ? _supportPolygon : hasSupportToPolygon;

	// Chrome / Safari
	if(typeof(element.style.webkitClipPath) !== 'undefined'){

		element.style.webkitClipPath = 'polygon(' + pathPoints + ')';

		// Unprefixed support
	} else if(_supportPolygon){

		element.style.clipPath = 'polygon(' + pathPoints + ')';

		// SVG
	} else {
		//Edge
		if(window.navigator.userAgent.indexOf("Edge") > -1){

			SVGPolyfill(element, pathPoints, true);

			//Other
		}else{
			SVGPolyfill(element, pathPoints);
		}
	}
}

`

**Comment by AlfonsoFilho** [comment]
@cvaize That is great! Whenever you think your code is ready, please feel free to open a PR.

**Comment by cvaize** [comment]
Sorry for the delay. There was a lot of work. As promised. See the [fork](https://github.com/cvaize/ClipPath). I added polyfill for Edge. Tested with % and px units. Works in Chrome, Firefox, Edge. In Edge, it works only with fixed border sizes (see the example index.html). And polyfill works only % or only px.[Here is the explanation](https://github.com/andrusieczko/clip-path-polygon/issues/16#issuecomment-180772453).

**Comment by cvaize** [comment]
Please release the new version 1.2.0. I noticed that the npm version 1.1.0 package does not have my pull request
@AlfonsoFilho

**Comment by AlfonsoFilho** [comment]
@cvaize sorry for the delay. 1.2.0 was published. Thanks for the PR.
