### ISSUE TITLE
it's a trap

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [AlfonsoFilho/ClipPath#7]
> Cross-browser clip-path polyfill

Nope. Please don't promise things that will not work by design.

**Comment by AlfonsoFilho** [comment]
This is an opensource project. Please, feel free to contribute and improve this library.

**Comment by AWqxKAWERbXo** [comment]
It is neither cross-browser nor a polyfill. It does not simulate features within a browser engine that can't work with "clip-path", which is the definition of a polyfill.

It's just wrong. Please update the repository description as I can't make a PR for that.
