### ISSUE TITLE
Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_1_clip_path___default(...) is not a function

### ISSUE THREAD

**Issue by pimmesz** [AlfonsoFilho/ClipPath#8]
Getting the following error when I try to execute the ClipPath on a element:

Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_1_clip_path___default(...) is not a function

Known error?

**Comment by AlfonsoFilho** [comment]
This library doesn't export default value. It should work fine importing like: 
```javascript
import { ClipPath } from 'clip-path';
```
or 
```javascript
import * as ClipPath from 'clip-path';
```
